import matplotlib.pyplot as plt

from SuspensionModel.noise.typeA import geophone,lvdt
from SuspensionModel.noise import seismicnoise

seis_h_99 = seismicnoise(unit='m',percentile='99',axis='hor')
seis_h_90 = seismicnoise(unit='m',percentile='90',axis='hor')
seis_h_01 = seismicnoise(unit='m',percentile='1' ,axis='hor')
seis_h_50 = seismicnoise(unit='m',percentile='50',axis='hor')
seis_h_10 = seismicnoise(unit='m',percentile='10',axis='hor')
seis_v_99 = seismicnoise(unit='m',percentile='99',axis='vert')
seis_v_90 = seismicnoise(unit='m',percentile='90',axis='vert')
seis_v_01 = seismicnoise(unit='m',percentile='1' ,axis='vert')
seis_v_50 = seismicnoise(unit='m',percentile='50',axis='vert')
seis_v_10 = seismicnoise(unit='m',percentile='10',axis='vert')
lvdt_ip_l = lvdt('IPL')
lvdt_ip_t = lvdt('IPT')
lvdt_ip_y = lvdt('IPY')
lvdt_gas_f0 = lvdt('GASF0')
lvdt_bf_l = lvdt('BFL')
lvdt_bf_t = lvdt('BFT')
lvdt_bf_v = lvdt('BFV')
lvdt_bf_p = lvdt('BFP')
lvdt_bf_y = lvdt('BFY')
lvdt_bf_r = lvdt('BFR')
geo_l = geophone(unit='m')
geo_t = geophone(unit='m')
geo_y = geophone(unit='m')

fig,ax = plt.subplots(1,1,figsize=(9,6))
plt.title('Horizontal and Vertical')
ax.plot_mmm(seis_h_50,seis_h_01,seis_h_99,color='k',alpha=0.1,label='hori.')
ax.plot_mmm(seis_h_50,seis_h_10,seis_h_90,color='k')
ax.plot_mmm(seis_v_50,seis_v_01,seis_v_99,color='m',alpha=0.1,label='vert.')
ax.plot_mmm(seis_v_50,seis_v_10,seis_v_90,color='m')
ax.loglog(lvdt_ip_l,label='IP_LVDT_L')
ax.loglog(lvdt_ip_t,label='IP_LVDT_T')
ax.loglog(lvdt_gas_f0,label='F0_LVDT_GAS')
ax.loglog(lvdt_bf_l,label='BF_LVDT_L')
ax.loglog(lvdt_bf_t,label='BF_LVDT_T')
ax.loglog(lvdt_bf_v,label='BF_LVDT_V')
ax.loglog(geo_l,label='IP_GEO_L')
ax.loglog(geo_t,label='IP_GEP_T')
ax.set_ylabel('Displacement [m/rtHz]')
ax.set_ylim(1e-12,1e-5)
ax.set_xlim(1e-2,1e2)
ax.grid(which='major',linestyle='--')
ax.grid(which='minor',linestyle=':')
ax.legend()
ax.set_xlabel('Frequency [Hz]')
plt.savefig('sens_noise_lvdt_acc_HTV.png')
plt.close()

fig,ax = plt.subplots(1,1,figsize=(9,6))
plt.title('Pit and Yaw and Roll')
ax.loglog(lvdt_ip_y,label='IP_LVDT_Y')
ax.loglog(lvdt_bf_p,label='BF_LVDT_P')
ax.loglog(lvdt_bf_y,label='BF_LVDT_Y')
ax.loglog(lvdt_bf_r,label='BF_LVDT_R')
ax.loglog(geo_y,label='IP_GEO_Y')
ax.set_ylabel('Angle [rad/rtHz]')
ax.set_ylim(1e-12,1e-5)
ax.set_xlim(1e-2,1e2)
ax.grid(which='major',linestyle='--')
ax.grid(which='minor',linestyle=':')
ax.legend()
ax.set_xlabel('Frequency [Hz]')
plt.savefig('sens_noise_lvdt_acc_PYR.png')
plt.close()
