(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
Off[General::spell,General::spell1]



(* ::Input::Initialization:: *)
Off[LinearSolve::luc]



(* ::Input::Initialization:: *)
Off[Syntax::stresc]


(* ::Input::Initialization:: *)
<<"mod/StatusWindow.m"


(* ::Input::Initialization:: *)
mod$OpenStatus;


(* ::Input::Initialization:: *)
mod$WriteStatus["Importing the Mathematica package PlotLegends`..."];
<<"PlotLegends`"


(* ::Input::Initialization:: *)
mod$WriteStatus["Importing unit system and physical constants..."];
<<"mod/Units.m"


(* ::Input::Initialization:: *)
mod$WriteStatus["Importing 3D graphics module for eigenmode plot..."];
<<"mod/Graphics3D.m"


(* ::Input::Initialization:: *)
mod$WriteStatus["Importing vibration isolation system utility package..."];
<<"mod/visUtil.m"


(* ::Input::Initialization:: *)
mod$WriteStatus["Importing user interface package..."];
<<"mod/Interface.m"


(* ::Input::Initialization:: *)
mod$WriteStatus["Packages have been imported."];


(* ::Input::Initialization:: *)
mod$WriteStatus["Now opening SUMCON..."];


(* ::Input::Initialization:: *)
titleSUMCON=Import["SUMCON.PNG"];
mod$StartSUMCON;


(* ::Input::Initialization:: *)
mod$CloseStatus;
