(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



kg=1.0;meter=1.0;rad=1.0;sec=1.0;Kervin=1.0;(*Basical Set*)
cm=10^(-2)meter;mm=10^(-3)meter; km=10^(3)meter;(*Length*)
gram=10^(-3)kg; mg=10^(-6)kg;(*Mass*)
deg=(N[Pi]/180.)rad; mrad=10^(-3)rad;urad=10^(-6)rad;(*Angle*)
Hz=1/sec;mHz=10^(-3)Hz; kHz=10^(3)Hz;(*Frequency*)
Newton=kg*meter/sec^(-2);kN=10^(3)Newton;mN=10^(-3)Newton;(*Force*)
Pa=Newton/meter^(2);MPa=10^(6)Pa;GPa=10^(9)Pa;(*Pressure*)
J=Newton*meter;kJ=10^(3)J;(*Energy*)



g=9.81 meter*sec^(-2); (*local gravity constant*)
kB=1.3806503*10^(-23) J/Kervin;(*Boltzman constant*)

